# https://squidfunk.github.io/mkdocs-material/creating-your-site/
# https://www.mkdocs.org/user-guide/configuration/

site_name: Vorburger.ch's Agentic AI Assistant
site_url: https://ai.vorburger.ch
repo_url: https://github.com/enola-dev/vorburger-ai-assistant
edit_uri: blob/main/docs/
copyright: Copyright &copy; 2025 Michael Vorburger.ch <https://www.vorburger.ch>

nav:
  - Home: index.md
  - Usage:
      - Install: install.md
      - Use: use.md
  - Development:
      # TODO - Contributing: development/contributing.md
      - Files & Directory: files.md

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn

theme:
  logo: images/logo.png
  favicon: images/logo.png
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.top
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - search.suggest
    - search.share
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

markdown_extensions:
  - footnotes
  - tables
  - smarty
  - toc:
      permalink: true
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  # https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  - pymdownx.magiclink
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
    # anchor_linenums: true
    # line_spans: __span
    # pygments_lang_class: true
  # https://squidfunk.github.io/mkdocs-material/reference/diagrams/
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  analytics:
    provider: google
    property: G-W0WFEQPB8E

plugins:
  - search

  # https://github.com/mondeja/mkdocs-include-markdown-plugin (ASL)
  # Possible alternative: https://github.com/cmacmackin/markdown-include (GPL)
  - include-markdown

  - git-revision-date-localized:
      strict: true

  # TODO Activate the following plugin once I will pay $15/month for
  # https://squidfunk.github.io/mkdocs-material/insiders/
